import uuid
import os
from typing import Dict, Any, List

from fastapi import FastAPI, HTTPException
from a2a_models import A2ARequest, A2AResponse, A2A_PROTOCOL_VERSION, Meta
from dotenv import load_dotenv
from openai import OpenAI

load_dotenv()
client = OpenAI(api_key=os.getenv("OPENAI_API_KEY"))

app = FastAPI(title="Hotel Agent (A2A + OpenAI LLM)")

SECRET_TOKEN = "SECRET123"
AGENT_ID = "hotel-agent"

@app.post("/a2a", response_model=A2AResponse)
async def handle_a2a(request: A2ARequest) -> A2AResponse:

    if request.protocol != A2A_PROTOCOL_VERSION:
        raise HTTPException(400, "Unsupported protocol")

    if request.receiver != AGENT_ID:
        raise HTTPException(400, "Wrong receiver")

    if request.security.token != SECRET_TOKEN:
        raise HTTPException(403, "Invalid token")

    try:
        if request.capability == "search_hotels":
            result = handle_search_hotels(request)
        elif request.capability == "book_room":
            result = handle_book_room(request)
        else:
            return build_error(request, "UNKNOWN_CAPABILITY", "Capability not supported", 400)

    except Exception as ex:
        return build_error(request, "INTERNAL_ERROR", str(ex), 500)

    return A2AResponse(
        protocol=A2A_PROTOCOL_VERSION,
        message_id=str(uuid.uuid4()),
        correlation_id=request.message_id,
        sender=AGENT_ID,
        receiver=request.sender,
        status="SUCCESS",
        status_code=200,
        result=result,
        meta=Meta(source_channel=AGENT_ID, trace_id=request.meta.trace_id if request.meta else None),
    )
# ---------------------- CAPABILITY IMPLEMENTATIONS ----------------------

def handle_book_room(request: A2ARequest) -> Dict[str, Any]:
    hotel_name = request.payload["hotel_name"]
    guest_name = request.payload["guest_name"]
    check_in = request.payload["check_in"]
    check_out = request.payload["check_out"]

    reservation_id = str(uuid.uuid4())
    total_price = 360.0

    confirmation_message = llm_booking_confirmation(
        reservation_id, hotel_name, guest_name, check_in, check_out
    )

    return {
        "reservation_id": reservation_id,
        "hotel_name": hotel_name,
        "guest_name": guest_name,
        "total_price": total_price,
        "currency": "USD",
        "confirmation_text": confirmation_message,
    }



def handle_search_hotels(request: A2ARequest) -> Dict[str, Any]:
    city = request.payload["city"]
    check_in = request.payload["check_in"]
    check_out = request.payload["check_out"]

    hotels = dummy_hotel_search(city)
    print(f" Hotels found:=========", hotels)

    summary = llm_summarize_hotels(city, check_in, check_out, hotels)
    print(" Summary generated by LLM:=====", summary)
    return {
        "hotels": hotels,
        "summary": summary,
    }


def dummy_hotel_search(city: str) -> List[Dict[str, Any]]:
    hotels = [
        {"name": "Riverside Grand", "price": 185, "rating": 4.6},
        {"name": "Historic Square Inn", "price": 150, "rating": 4.3},
        {"name": "Budget Stay", "price": 95, "rating": 3.9},
    ]
    for hotel in hotels:
        hotel["city"] = city

    return hotels


def llm_summarize_hotels(city, check_in, check_out, hotels):
    prompt = f"""
You are the hotel agent. Summarize the following hotel options for a user.

City: {city}
Dates: {check_in} to {check_out}

Hotels:
{hotels}

Write a helpful, short summary recommending the best value and best luxury option.
"""

    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[{"role": "user", "content": prompt}],
    )
    #print(" LLM Response:=====", response)

    return  response.choices[0].message.content



def llm_booking_confirmation(res_id, hotel, guest, check_in, check_out):
    prompt = f"""
Write a 3-line friendly hotel booking confirmation.

Reservation ID: {res_id}
Hotel: {hotel}
Guest: {guest}
Check-in: {check_in}
Check-out: {check_out}
"""

    response = client.chat.completions.create(
        model="gpt-4.1-mini",
        messages=[{"role": "user", "content": prompt}],
    )

    return  response.choices[0].message.content


def build_error(request, code, message, status=500):
    return A2AResponse(
        protocol=A2A_PROTOCOL_VERSION,
        message_id=str(uuid.uuid4()),
        correlation_id=request.message_id,
        sender=AGENT_ID,
        receiver=request.sender,
        status="ERROR",
        status_code=status,
        error={"code": code, "message": message},
    )


# ----------------------------- ENTRYPOINT -------------------------------

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("hotel_agent:app", host="0.0.0.0", port=8000, reload=True)
